# Generated by Django 3.2.7 on 2023-09-05 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20230817_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='google_token',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
