# Generated by Django 3.2.7 on 2023-09-08 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_google_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='youtube',
        ),
    ]
