# Generated by Django 3.2.7 on 2023-12-19 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_feed'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='feed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.feed'),
        ),
        migrations.CreateModel(
            name='NestedReply',
            fields=[
                ('nested_reply_id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.reply')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
            options={
                'db_table': 'nested_reply',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='like',
            name='nested_reply',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.nestedreply'),
        ),
    ]
