# Generated by Django 4.2.8 on 2024-01-09 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20231219_1940'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='following',
            name='follow_user',
        ),
        migrations.RemoveField(
            model_name='following',
            name='hashtag',
        ),
        migrations.RemoveField(
            model_name='following',
            name='user',
        ),
        migrations.RemoveField(
            model_name='like',
            name='feed',
        ),
        migrations.RemoveField(
            model_name='like',
            name='nested_reply',
        ),
        migrations.RemoveField(
            model_name='like',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='like',
            name='reply',
        ),
        migrations.RemoveField(
            model_name='like',
            name='user',
        ),
        migrations.DeleteModel(
            name='Feed',
        ),
        migrations.DeleteModel(
            name='Following',
        ),
        migrations.DeleteModel(
            name='Hashtag',
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
