# Generated by Django 4.2.8 on 2024-01-19 22:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
        ('users', '0008_remove_following_follow_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='feed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.feed'),
        ),
    ]
