# Generated by Django 3.2.7 on 2023-08-04 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_auto_20230802_1716'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='movieepisode',
            table='movie_episodes',
        ),
    ]
