# Generated by Django 3.2.7 on 2023-08-16 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_alter_movieepisode_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='spoiler',
            field=models.BooleanField(default=False),
        ),
    ]
