# Generated by Django 3.2.7 on 2023-08-17 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
