# Generated by Django 3.2.7 on 2023-08-28 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0009_auto_20230828_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='creeated_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='episode',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
