# Generated by Django 3.2.7 on 2023-08-28 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0010_auto_20230828_1119'),
    ]

    operations = [
        migrations.RenameField(
            model_name='episode',
            old_name='creeated_at',
            new_name='created_at',
        ),
    ]
