# Generated by Django 3.2.7 on 2023-08-28 04:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0011_rename_creeated_at_episode_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('channel_id', models.CharField(max_length=100, null=True)),
                ('description', models.TextField(default='등록된 소개글이 없습니다.')),
                ('image_url', models.URLField(max_length=500)),
                ('subscriber_count', models.IntegerField(blank=True, default=0, null=True)),
                ('view_count', models.IntegerField(blank=True, default=0, null=True)),
                ('video_count', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='movie',
            name='channel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='movies.channel'),
        ),
    ]
