# Generated by Django 3.2.7 on 2023-08-28 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0012_auto_20230828_1316'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='channel',
            table='channels',
        ),
    ]
