# Generated by Django 3.2.7 on 2023-08-28 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0014_remove_channel_video_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='handle',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
