# Generated by Django 3.2.7 on 2023-08-28 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0015_channel_handle'),
    ]

    operations = [
        migrations.RenameField(
            model_name='channel',
            old_name='image_url',
            new_name='thumbnail',
        ),
        migrations.RenameField(
            model_name='channel',
            old_name='name',
            new_name='title',
        ),
        migrations.AddField(
            model_name='channel',
            name='published_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='channel',
            name='video_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
