# Generated by Django 3.2.7 on 2023-08-28 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0016_auto_20230828_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
