# Generated by Django 3.2.7 on 2023-08-28 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0017_channel_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='playlist',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
