# Generated by Django 3.2.7 on 2023-09-04 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0021_auto_20230904_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='description',
            field=models.TextField(default='등록된 소개글이 없습니다.'),
        ),
    ]
