# Generated by Django 3.2.7 on 2023-09-04 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0022_episode_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='duration',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
