# Generated by Django 3.2.7 on 2023-09-08 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0023_alter_episode_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='totalComments',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='totalLikes',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='totalViews',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
