# Generated by Django 3.2.7 on 2023-09-08 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0024_auto_20230908_1052'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='totalComments',
            new_name='total_comments',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='totalLikes',
            new_name='total_likes',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='totalViews',
            new_name='total_views',
        ),
    ]
