# Generated by Django 3.2.7 on 2023-09-18 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0025_auto_20230908_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='subscriber_count',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='channel',
            name='video_count',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='channel',
            name='view_count',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='episode',
            name='commentCount',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='episode',
            name='likeCount',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='episode',
            name='viewCount',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='total_comments',
            field=models.BigIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='total_likes',
            field=models.BigIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='total_views',
            field=models.BigIntegerField(default=0, null=True),
        ),
    ]
