# Generated by Django 3.2.7 on 2023-09-18 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0026_auto_20230918_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='name',
            field=models.CharField(max_length=500),
        ),
    ]
