# Generated by Django 3.2.7 on 2023-11-09 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0028_auto_20231109_2205'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='is_new',
            field=models.BooleanField(default=False),
        ),
    ]
