# Generated by Django 3.2.7 on 2023-11-13 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0029_movie_is_new'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='is_new',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
