# Generated by Django 3.2.7 on 2023-11-14 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0031_playhistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='grade',
        ),
        migrations.AlterModelTable(
            name='playhistory',
            table='play_histories',
        ),
    ]
