# Generated by Django 3.2.7 on 2023-11-19 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0032_auto_20231115_0858'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(max_length=20)),
                ('rank', models.JSONField(blank=True, null=True)),
                ('category', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ranks',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='movie',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
