# Generated by Django 3.2.7 on 2023-11-20 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0036_auto_20231120_0811'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='tags',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
